### ISSUE TITLE
Cannot get notification to fire

### ISSUE THREAD

**Issue by BenWoodford** [Samfox2/homebridge-videodoorbell#5] opened 2017-12-24 16:41 UTC
I'm posting to the port and it HTTP 200s all fine and well, but I don't appear to be getting any notifications from it on my phone.

Should the doorbell only show as a single device (a camera) or should there be a second device for the actual doorbell and the camera is a secondary accessory?

**Comment by Samfox2** [comment] 2017-12-24 18:50
Hi. It should appear as a single device. If it‘s not working please try another port, maybe it‘s already in use.

**Comment by BenWoodford** [comment] 2017-12-24 19:15
The port is fine, I can see the web server output. Just don’t get any notifications when I trigger it for some reason

**Comment by BenWoodford** [comment] 2018-01-07 12:02
It's worth mentioning that I don't have a notifications option on the camera that is exposed by this. For motion sensors there's a notifications setting on the accessory that I need to set. That isn't present here.

Could that be related? I don't have a homekit-compatible doorbell to use as a control test.

**Comment by Samfox2** [comment] 2018-01-07 12:34
No, that‘s ok. Have you tried to sign out and sign in to your icloud account?

**Comment by BenWoodford** [comment] 2018-01-08 13:48
I'll give it a go. I'll try running homebridge in debug mode too, maybe it'll give some info on what's going wrong.

**Comment by BenWoodford** [comment] 2018-01-08 14:28
Nope, nothing. Unless perhaps my homebridge install is out of date...

Nope. Updated and still doesn't notify.

**Comment by Samfox2** [comment] 2018-01-08 15:02
hmm, what does debug output say?

**Comment by BenWoodford** [comment] 2018-01-08 17:57
Not much, just shows the "Ding dong!" message

**Comment by Samfox2** [comment] 2018-01-10 09:24
#8 Maybe this solves your problem too...

**Comment by BenWoodford** [comment] 2018-01-10 10:18
Oh the camera portion works, it's the notification portion that doesn't.

**Comment by Samfox2** [comment] 2018-01-15 13:15
Maybe this helps

https://github.com/KhaosT/homebridge-amazondash/issues/28#event-1423958881

**Comment by BenWoodford** [comment] 2018-01-15 16:02
I've already tried all of that unfortunately. Deleting it, restarting, update, etc. Nothing seems to stick.

Are you running the latest iOS version?

**Comment by Samfox2** [comment] 2018-01-15 16:56
Yes

**Comment by BenWoodford** [comment] 2018-01-27 12:10
A thought: could it be the RTSP stream I’m using isn’t liked by HomeKit?

**Comment by Samfox2** [comment] 2018-01-27 14:08
If you can see a picture/stream at the camera in your home app this should not csuse any issues.

**Comment by Samfox2** [comment] 2018-03-03 09:11
Could you try the updated version? Does at least the button trigger work?

**Comment by BenWoodford** [comment] 2018-03-04 12:28
Nope, updated homebridge and the plugin, nothing has changed. I still just have one camera device, no other buttons anywhere.

Going to update my phone as it’s a few minor versions out.

Could you take some screenshots of what everything is meant to look like?

**Comment by normen** [comment] 2018-03-04 16:09
I don‘t think the issue is with this plugin. Make sure you didn‘t disable messages for the Home app on your Phone.

**Comment by BenWoodford** [comment] 2018-03-04 16:52
Ahah, seems to be working now! Not sure what change fixed it, but it’s working via button and URL. :)

**Comment by normen** [comment] 2018-03-04 18:13
As said probably something on your side, none of the changes could have affected this in any way.

**Comment by Samfox2** [comment] 2018-03-04 20:14
Great, working after months... :-) Closing this issue now - finally.

**Closed** 2018-03-05 23:50 UTC
